name: Run Python Script on PR Creation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have a requirements.txt file with dependencies

    - name: Get commit ID
      id: commit
      run: echo "::set-output name=commit_id::${{ github.sha }}"

    - name: Get changed files
      id: files
      run: echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

    - name: Run Python script
      run: python python.py ${{ steps.commit.outputs.commit_id }} ${{ steps.files.outputs.changed_files }} ${{ github.event.number }}
      env:
        GITHUB_TOKEN: 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
        PULL_REQUEST_NUMBER: ${{ github.event.number }}
