name: Run Python Script on PR Creation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have a requirements.txt file with dependencies

    - name: Get commit ID
      id: commit
      run: echo "::set-output name=commit_id::${{ github.sha }}"

    - name: Get changed files
      id: files
      run: |
        files=$(curl -s -H "Authorization: Bearer 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" \
                     -H "Accept: application/vnd.github.v3+json" \
                     ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files \
                     | jq -r '.[] | .filename')
        echo "::set-output name=changed_files::${files}"

    - name: Run Python script
      run: python python.py ${{ steps.commit.outputs.commit_id }} ${{ steps.files.outputs.changed_files }} ${{ github.event.number }}
      env:
        GITHUB_TOKEN: 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
        PULL_REQUEST_NUMBER: ${{ github.event.number }}
